export enum RequestType {
  GetDetails,
  AddDetails,
  UpdateDetails,
  DeleteDetails,
  GetConditions,
  AddCondition,
  UpdateCondition,
  DeleteCondition,
  GetMedications,
  AddMedication,
  UpdateMedication,
  DeleteMedication,
  DeleteDatabase,
}
